version: 0.2

phases:
  install:
    commands:
      - echo Installing Amazon Corretto 17...
      - yum remove -y java-11-amazon-corretto  # Remove Java 11 if installed
      - yum install -y java-17-amazon-corretto
      - export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version  # Confirm Java 17 installation
      - echo Installing Android SDK and Flutter...
      # Install Android SDK
      - mkdir -p /android-sdk && cd /android-sdk
      - curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
      - unzip commandlinetools.zip -d cmdline-tools
      - mkdir -p cmdline-tools/latest
      - mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
      - export ANDROID_HOME=/android-sdk
      - export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
      - echo Installing required Android SDK components...
      - yes | sdkmanager --licenses
      - sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"
      # Install Flutter
      - cd / && git clone https://github.com/flutter/flutter.git -b stable
      - export PATH=$PATH:/flutter/bin
      - flutter doctor
      - flutter precache
      - flutter doctor --android-licenses
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR # Navigate to the source directory
      - echo Building Flutter APK...
      - pwd                   # Confirm the current directory
      - ls                    # List files in the project directory
      - flutter clean
      - flutter build apk --release  --verbose
  post_build:
    commands:
      - echo Build complete.

artifacts:
  files:
    - '**/app-release.apk'