// Mocks generated by Mockito 5.4.4 from annotations
// in transaction_mobile_app/test/helper/helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_contacts/flutter_contacts.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:transaction_mobile_app/data/repository/contact_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRepository extends _i1.Mock implements _i2.ContactRepository {
  MockContactRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<dynamic>> checkMyContacts(
          {required List<_i4.Contact>? contacts}) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkMyContacts,
          [],
          {#contacts: contacts},
        ),
        returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> searchContactsByTag(
          {required String? query}) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchContactsByTag,
          [],
          {#query: query},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<_i4.Contact>> fetchLocalContacts() => (super.noSuchMethod(
        Invocation.method(
          #fetchLocalContacts,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Contact>>.value(<_i4.Contact>[]),
      ) as _i3.Future<List<_i4.Contact>>);
}
